#!/bin/env bash

case "$1" in
    -h|--help) cat<<EOF
Usage: gbc [ -h ] (recent branch number | <git checkout options ...>)

gbc script checks out git branch.
See recent branch number in gbr
EOF
       exit 1 ;;
esac

. "$(dirname $0)"/find-root-dir.sh


CURRENT_BRANCH="$(gbn)"

if [[ "$1" =~ ^[0-9]+$ ]] ; then
   TARGET_BRANCH=$(sed "$1"'!d' "$BRANCH_LRU")
else
   TARGET_BRANCH="$1"
fi

shift

if [ -f "$BRANCH_LRU" ] ; then
    sed -i -e "/^$CURRENT_BRANCH"'$/d' "$BRANCH_LRU"
    sed -i -e "/^$TARGET_BRANCH"'$/d' "$BRANCH_LRU"
    sed -i -e "1i $CURRENT_BRANCH" "$BRANCH_LRU"
    sed -i -e 11d "$BRANCH_LRU"
fi

[ -f "$BRANCH_LRU" ] || { echo "$CURRENT_BRANCH" >> "$BRANCH_LRU"; }
[ $(wc -l < "$BRANCH_LRU") -le 2 ] && { echo "$CURRENT_BRANCH" >> "$BRANCH_LRU"; }


[ -n "$TARGET_BRANCH" ] && git checkout "$TARGET_BRANCH" "$@"
