#!/bin/env bash

case "$1" in
    -h|--help) cat<<EOF
Usage: gop [ -h ] [ ( <recent branch number> | <branch = current branch> )

gop script pushes changes to origin branch.
See recent branch number in gbr

gop 1
gop 1:xxx
gop # git push curent-branch:curent-branch
EOF
       exit 1 ;;
esac

. "$(dirname $0)"/find-root-dir.sh


CURRENT_BRANCH="$(gbn)"

if [[ "$1" =~ ^[0-9]+$ ]] ; then
   B=$(sed "$1"'!d' "$BRANCH_LRU")
   [ -n "$B" ] && git push origin "$B:$B"
elif [[ "$1" == "" ]] ; then
    git push origin "$CURRENT_BRANCH:$CURRENT_BRANCH"
elif [[ "$1" =~ ^([0-9]+):([a-zA-Z_0-9-]+)$ ]] ; then
   B=$(sed "${BASH_MATCHES[1]}"'!d' "$BRANCH_LRU")
   [ -n "$B" ] && git push origin "$B:${BASH_MATCHES[1]}"
else
    git push origin "$@"
fi
